version: '3.0'
services:
 web:
    image: nginx:latest
    container_name: 'webserver'
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./www:/var/www/html:rw
        - ./config/nginx:/etc/nginx/conf.d:rw
        - ./logs/nginx:/var/log/nginx:rw
        - ./config/ssl:/etc/nginx/ssl:rw
    links:
        - php:php
        - mysql:mysql
    restart: 'always'
 mysql:
    image: mysql:5.7
    container_name: 'mysql'
    restart: 'always'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    env_file:
      - .env
    command: mysqld --max_allowed_packet=128M
 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - mysql:mysql
    env_file:
      - .env
    ports:
      - '8000:80'
 redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "6379:6379"
    
 php:
    image: cybersiegelab/php-fpm_5.6.x:latest
    # build:
    #   context: config/php-fpm
    container_name: 'php'
    volumes:
        - ./www:/var/www/html
    links:
        - mysql:mysql
